### ISSUE TITLE
Integrate Firefox containers

### ISSUE THREAD

**Issue by ghost** [web-launcher/web-launcher#31]
It would be great if this could be integrated with the containers extension.
It could be a different page setup based on the container where the new tab is opened.
Otherwise would be good to set the target container when a link is "Open in new Tab"

**Comment by jwr1** [comment]
Are you talking about the [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) extension?

**Comment by ghost** [comment]
> Are you talking about the [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) extension?

I've enabled it from Firefox Settings here:
![image](https://user-images.githubusercontent.com/68850980/208648433-8a777b0a-89a0-48a5-8ea0-41dcaf3f0632.png)

When I go to that extension's page it looks not installed
![image](https://user-images.githubusercontent.com/68850980/208648735-bd492e52-4f2b-443f-9412-6b60c87c7db0.png)

That said, I think it's the same functionality.

**Comment by jwr1** [comment]
I was already thinking about supporting this, so I'll probably add it in with the next update now that I know someone else would use it.

**Comment by jwr1** [comment]
The only problem I see with this is that it would enable containers for anyone that has the extension installed. It requires the [contextualIdentities](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contextualIdentities) permission which can not be an optional permission.

**Comment by ghost** [comment]
> The only problem I see with this is that it would enable containers for anyone that has the extension installed. It requires the [contextualIdentities](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contextualIdentities) permission which can not be an optional permission.

> From Firefox 57 onwards, if an extension that uses the contextualIdentities API is installed, then the contextual identities feature will be enabled automatically. 

Yeah, this sounds bad.
I've tried adding Tree Style Tab in a brand new profile and it did install and enable containers automatically
![image](https://user-images.githubusercontent.com/68850980/208688981-77241638-4ae4-4622-8cd4-29164c152a18.png)

Of topic:
> "Contextual identities", also known as "containers", are a browser feature which addresses the idea that users assume multiple identities when browsing the web, and wish to maintain some separation between these identities. 

The wording on this is kind of funny. I for one don't identify with containers nor browsers 😂

**Comment by jwr1** [comment]
I could also create another extension with the necessary permissions and use [runtime.sendMessage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/sendMessage) to communicate with the current extension. To use containers, you would just have to have both extensions installed.

**Comment by jwr1** [comment]
Implemented in fb7f900077b1e22dfeffe68f0d9ef292cf3a7348.
